services:
  db:
    image: jvboronatjosep/pinacoteca_db:v1
    container_name: contenedorPinacoteca_db
    ports:
      - "3306:3306"
  php:
    image: jvboronatjosep/pinacoteca_app:v1
    container_name: contenedorPinacoteca_app
    ports:
      - "8080:80"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedorPhpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: contrasenyaRoot
    ports:
      - "8081:80"
    depends_on:
      - db